#!/usr/bin/env python3
"""
Tull Hydroponics - Credential Setup Script
==========================================

Run this script to generate hashed credentials for local development.
It will create/update your vars.env file with valid password hashes.

Usage:
    python setup_credentials.py

This will prompt you for usernames and passwords, then generate
the appropriate hashes and save them to vars.env.
"""

import os
import sys

def main():
    # Check for werkzeug
    try:
        from werkzeug.security import generate_password_hash
    except ImportError:
        print("=" * 60)
        print("ERROR: werkzeug not installed")
        print("=" * 60)
        print()
        print("Run: pip install werkzeug")
        print("Or:  pip install -r requirements.txt")
        sys.exit(1)

    print("=" * 60)
    print("TULL HYDROPONICS - Credential Setup")
    print("=" * 60)
    print()
    print("This will create a vars.env file for local development.")
    print("Press Enter to use default values shown in [brackets].")
    print()

    # Admin credentials
    print("ADMIN CREDENTIALS")
    print("-" * 40)
    admin_username = input("  Admin username [admin]: ").strip() or "admin"
    admin_password = input("  Admin password [admin123]: ").strip() or "admin123"

    admin_username_hash = generate_password_hash(admin_username)
    admin_password_hash = generate_password_hash(admin_password)
    print()

    # Investor credentials
    print("INVESTOR CREDENTIALS")
    print("-" * 40)
    investor_username = input("  Investor username [investor]: ").strip() or "investor"
    investor_password = input("  Investor password [invest123]: ").strip() or "invest123"

    investor_username_hash = generate_password_hash(investor_username)
    investor_password_hash = generate_password_hash(investor_password)
    print()

    # Generate secret key
    import secrets
    secret_key = secrets.token_hex(32)

    # Create vars.env content
    env_content = f'''# ============================================================================
# TULL HYDROPONICS - Local Development Environment Variables
# ============================================================================
# Generated by setup_credentials.py
# DO NOT commit this file to version control!
#
# Test Credentials:
#   Admin:    {admin_username} / {admin_password}
#   Investor: {investor_username} / {investor_password}
# ============================================================================

# Flask Configuration
FLASK_SECRET_KEY={secret_key}
FLASK_ENV=development

# Main Domain (for Stripe redirects)
MAIN_DOMAIN=http://localhost:5000

# ============================================================================
# STRIPE CONFIGURATION
# ============================================================================
# Get TEST keys from: https://dashboard.stripe.com/test/apikeys
# Use test card: 4242 4242 4242 4242

STRIPE_SECRET_KEY=sk_test_your_test_key_here
STRIPE_PUBLISHABLE_KEY=pk_test_your_test_key_here
STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret_here
HP_PRICE_ID=price_your_test_price_id_here

# ============================================================================
# POSTMARK CONFIGURATION
# ============================================================================
POSTMARK_SERVER_TOKEN=your_postmark_server_token_here
POSTMARK_SENDER_EMAIL=support@tullhydro.com

# ============================================================================
# ADMIN CREDENTIALS
# ============================================================================
# Username: {admin_username}
ADMIN_USERNAME_HASH={admin_username_hash}
ADMIN_PASSWORD_HASH={admin_password_hash}

# ============================================================================
# INVESTOR CREDENTIALS
# ============================================================================
# Username: {investor_username}
INVESTOR_USERNAME_HASH={investor_username_hash}
INVESTOR_PASSWORD_HASH={investor_password_hash}
'''

    # Check if vars.env exists
    if os.path.exists('vars.env'):
        print("WARNING: vars.env already exists!")
        overwrite = input("Overwrite? [y/N]: ").strip().lower()
        if overwrite != 'y':
            print("Cancelled. Your existing vars.env was not modified.")
            return

    # Write to file
    with open('vars.env', 'w') as f:
        f.write(env_content)

    print("=" * 60)
    print("SUCCESS!")
    print("=" * 60)
    print()
    print("Created: vars.env")
    print()
    print("You can now run the application:")
    print("    python main.py")
    print()
    print("Login at http://localhost:5000/login")
    print(f"    Admin:    {admin_username} / {admin_password}")
    print(f"    Investor: {investor_username} / {investor_password}")
    print()
    print("Next steps:")
    print("  1. Add your Stripe test keys to vars.env")
    print("  2. Add your Postmark server token to vars.env")
    print("  3. See MANAGEMENT_GUIDE.md for full documentation")
    print()

if __name__ == "__main__":
    main()
