#!/usr/bin/env python3
"""
Tull Hydroponics - Credential Setup Script
==========================================

Run this script to configure local development credentials.
It will create/update your vars.env file with a bootstrap admin account.

Usage:
    python setup_credentials.py

After first run, manage all accounts via TullOps admin API.
"""

import os
import sys


def main():
    try:
        from werkzeug.security import generate_password_hash
    except ImportError:
        print("=" * 60)
        print("ERROR: werkzeug not installed")
        print("=" * 60)
        print()
        print("Run: pip install werkzeug")
        print("Or:  pip install -r requirements.txt")
        sys.exit(1)

    import secrets

    print("=" * 60)
    print("TULL HYDROPONICS - Credential Setup")
    print("=" * 60)
    print()
    print("This will create a vars.env file for local development.")
    print("Press Enter to use default values shown in [brackets].")
    print()

    # Admin bootstrap credentials
    print("ADMIN BOOTSTRAP (first-run account)")
    print("-" * 40)
    admin_email = input("  Admin email/username [admin]: ").strip() or "admin"
    admin_password = input("  Admin password [admin123]: ").strip() or "admin123"
    admin_display = input("  Display name [Admin]: ").strip() or "Admin"
    print()

    # Generate keys
    secret_key = secrets.token_hex(32)
    api_key = secrets.token_hex(32)

    env_content = f'''# ============================================================================
# TULL HYDROPONICS - Local Development Environment Variables
# ============================================================================
# Generated by setup_credentials.py
# DO NOT commit this file to version control!
#
# Bootstrap Admin: {admin_email} / {admin_password}
# ============================================================================

# Flask Configuration
FLASK_SECRET_KEY={secret_key}
FLASK_ENV=development

# Main Domain (for Stripe redirects)
MAIN_DOMAIN=http://localhost:5000

# ============================================================================
# STRIPE CONFIGURATION
# ============================================================================
# Get TEST keys from: https://dashboard.stripe.com/test/apikeys
# Use test card: 4242 4242 4242 4242

STRIPE_SECRET_KEY=sk_test_your_test_key_here
STRIPE_PUBLISHABLE_KEY=pk_test_your_test_key_here
STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret_here
HP_PRICE_ID=price_your_test_price_id_here

# ============================================================================
# POSTMARK CONFIGURATION
# ============================================================================
POSTMARK_SERVER_TOKEN=your_postmark_server_token_here
POSTMARK_SENDER_EMAIL=support@tullhydro.com

# ============================================================================
# ADMIN BOOTSTRAP (first-run only)
# ============================================================================
# Creates the initial admin account when the database is empty.
# After bootstrap, manage all accounts via TullOps admin API.

ADMIN_BOOTSTRAP_EMAIL={admin_email}
ADMIN_BOOTSTRAP_PASSWORD={admin_password}
ADMIN_BOOTSTRAP_DISPLAY_NAME={admin_display}

# ============================================================================
# ADMIN API KEY (for TullOps remote management)
# ============================================================================
ADMIN_API_KEY={api_key}

# ============================================================================
# SECURITY THRESHOLDS
# ============================================================================
AUTO_BAN_THRESHOLD=20
AUTO_BAN_WINDOW_HOURS=1
'''

    if os.path.exists('vars.env'):
        print("WARNING: vars.env already exists!")
        overwrite = input("Overwrite? [y/N]: ").strip().lower()
        if overwrite != 'y':
            print("Cancelled. Your existing vars.env was not modified.")
            return

    with open('vars.env', 'w') as f:
        f.write(env_content)

    print("=" * 60)
    print("SUCCESS!")
    print("=" * 60)
    print()
    print("Created: vars.env")
    print()
    print("You can now run the application:")
    print("    python main.py")
    print()
    print("Login at http://localhost:5000/login")
    print(f"    Admin: {admin_email} / {admin_password}")
    print()
    print("Next steps:")
    print("  1. Add your Stripe test keys to vars.env")
    print("  2. Add your Postmark server token to vars.env")
    print("  3. See MANAGEMENT_GUIDE.md for full documentation")
    print()


if __name__ == "__main__":
    main()
