#!/usr/bin/env python3
"""
Tull Hydroponics - Credential Setup Script
==========================================

Run this script to generate hashed credentials for local development.
It will create/update your vars.env file with valid password hashes.

Usage:
    python setup_credentials.py

This will prompt you for usernames and passwords, then generate
the appropriate hashes and save them to vars.env.
"""

import os
import sys

# Check for werkzeug
try:
    from werkzeug.security import generate_password_hash
except ImportError:
    print("Error: werkzeug not installed. Run: pip install werkzeug")
    sys.exit(1)

def generate_credentials():
    print("=" * 60)
    print("TULL HYDROPONICS - Credential Setup")
    print("=" * 60)
    print()
    
    # Admin credentials
    print("ADMIN CREDENTIALS")
    print("-" * 40)
    admin_username = input("Enter admin username [admin]: ").strip() or "admin"
    admin_password = input("Enter admin password [admin123]: ").strip() or "admin123"
    
    admin_username_hash = generate_password_hash(admin_username)
    admin_password_hash = generate_password_hash(admin_password)
    
    print(f"  Username: {admin_username}")
    print(f"  Password: {'*' * len(admin_password)}")
    print()
    
    # Investor credentials
    print("INVESTOR CREDENTIALS")
    print("-" * 40)
    investor_username = input("Enter investor username [investor]: ").strip() or "investor"
    investor_password = input("Enter investor password [invest123]: ").strip() or "invest123"
    
    investor_username_hash = generate_password_hash(investor_username)
    investor_password_hash = generate_password_hash(investor_password)
    
    print(f"  Username: {investor_username}")
    print(f"  Password: {'*' * len(investor_password)}")
    print()
    
    # Create or update vars.env
    env_content = f'''# ============================================================================
# TULL HYDROPONICS - Local Development Environment Variables
# ============================================================================
# Generated by setup_credentials.py
# DO NOT commit this file to version control!
# ============================================================================

# Flask Configuration
FLASK_SECRET_KEY=dev-secret-key-{os.urandom(8).hex()}
FLASK_ENV=development

# Main Domain (for Stripe redirects)
MAIN_DOMAIN=http://localhost:5000

# ============================================================================
# STRIPE CONFIGURATION (Use test keys)
# ============================================================================
# Get test keys from: https://dashboard.stripe.com/test/apikeys
STRIPE_SECRET_KEY=sk_test_your_test_key_here
STRIPE_PUBLISHABLE_KEY=pk_test_your_test_key_here
STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret_here
HP_PRICE_ID=price_your_test_price_id_here

# ============================================================================
# MAILGUN CONFIGURATION
# ============================================================================
MAIL_KEY=your_mailgun_api_key_here

# ============================================================================
# ADMIN CREDENTIALS
# ============================================================================
# Username: {admin_username}
ADMIN_USERNAME_HASH={admin_username_hash}
ADMIN_PASSWORD_HASH={admin_password_hash}

# ============================================================================
# INVESTOR CREDENTIALS  
# ============================================================================
# Username: {investor_username}
INVESTOR_USERNAME_HASH={investor_username_hash}
INVESTOR_PASSWORD_HASH={investor_password_hash}
'''
    
    # Write to file
    with open('vars.env', 'w') as f:
        f.write(env_content)
    
    print("=" * 60)
    print("SUCCESS! vars.env has been created/updated.")
    print("=" * 60)
    print()
    print("You can now run the application with:")
    print("    python main.py")
    print()
    print("Login credentials:")
    print(f"    Admin:    {admin_username} / {admin_password}")
    print(f"    Investor: {investor_username} / {investor_password}")
    print()

if __name__ == "__main__":
    generate_credentials()
